"""Harness generation and execution for kernel optimization.

Two harness types:
  1. Correctness harness — compares original vs optimized kernel outputs
  2. Performance harness — measures execution time with interleaved A/B testing

Each harness is a standalone Python script that the orchestrator writes
(via agent) and then executes via subprocess.
"""

from __future__ import annotations

import json
import os
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


# --------------------------------------------------------------------------- #
# Correctness Harness
# --------------------------------------------------------------------------- #

# Template for the correctness harness. The agent fills in:
#   {kernel_loader} — imports the kernel module
#   {test_inputs}   — generates diverse test inputs covering all code paths
#   {ref_runner}    — runs the reference (original) kernel
#   {evo_runner}    — runs the optimized (evolved) kernel
#   {comparator}    — compares results and determines pass/fail

CORRECTNESS_HARNESS_TEMPLATE = '''"""
Auto-generated correctness harness for kernel optimization.
Compares original kernel output against optimized kernel output.
Generated by MetaInfer evolve-kernel orchestrator.
"""
import importlib.util
import json
import sys
import traceback
from pathlib import Path

import torch


def load_kernel(filepath: str, fn_name: str = "{kernel_fn_name}"):
    """Load a kernel function from a Python file."""
    spec = importlib.util.spec_from_file_location("_kernel_mod", filepath)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, fn_name):
        raise ValueError(f"Function {{fn_name!r}} not found in {{filepath}}")
    return getattr(mod, fn_name)


def generate_test_inputs():
    """Generate diverse test inputs covering all kernel code paths.

    Returns a list of dicts, each with kwargs for the kernel function.
    THE AGENT MUST FILL THIS IN with inputs that cover:
      - Small / medium / large sizes
      - Even / uneven dimensions
      - Different dtypes if applicable
      - Edge cases (size=1, power-of-2, prime numbers, etc.)
      - Any internal branching conditions the kernel checks
    """
{test_inputs_body}
    return test_cases


def run_reference(kernel_fn, test_case):
    """Run the REFERENCE (original) kernel. AGENT FILLS IN."""
{ref_runner_body}
    return output


def run_evolved(kernel_fn, test_case):
    """Run the EVOLVED (optimized) kernel. AGENT FILLS IN."""
{evo_runner_body}
    return output


def compare(ref_output, evo_output):
    """Compare reference vs evolved outputs. AGENT FILLS IN.

    Returns (passed: bool, error: str, details: dict).
    """
{comparator_body}


def main():
    if len(sys.argv) < 2:
        print(json.dumps({{"passed": False, "error": "Usage: python harness.py <evolved_kernel.py>"}}))
        sys.exit(0)

    evolved_path = sys.argv[1]
    ref_path = "{ref_kernel_path}"

    try:
        ref_fn = load_kernel(ref_path, "{kernel_fn_name}")
        evo_fn = load_kernel(evolved_path, "{kernel_fn_name}")
    except Exception as e:
        print(json.dumps({{
            "passed": False,
            "error": f"Failed to load kernels: {{e}}",
            "traceback": traceback.format_exc()[:2000],
        }}))
        sys.exit(0)

    test_cases = generate_test_inputs()
    results = []
    all_passed = True
    first_error = None
    first_traceback = None

    for i, tc in enumerate(test_cases):
        try:
            ref_out = run_reference(ref_fn, tc)
            evo_out = run_evolved(evo_fn, tc)
            passed, error, details = compare(ref_out, evo_out)
            results.append({{
                "index": i,
                "name": tc.get("name", f"case_{{i}}"),
                "passed": passed,
                "error": error,
                "details": details,
            }})
            if not passed:
                all_passed = False
                if first_error is None:
                    first_error = error
                    first_traceback = details.get("traceback", "")
        except Exception as e:
            results.append({{
                "index": i,
                "name": tc.get("name", f"case_{{i}}"),
                "passed": False,
                "error": str(e)[:500],
                "traceback": traceback.format_exc()[:2000],
            }})
            all_passed = False
            if first_error is None:
                first_error = str(e)[:500]
                first_traceback = traceback.format_exc()[:2000]

    print(json.dumps({{
        "passed": all_passed,
        "error": first_error,
        "traceback": first_traceback,
        "total": len(test_cases),
        "passed_count": sum(1 for r in results if r["passed"]),
        "results": results,
    }}))


if __name__ == "__main__":
    main()
'''


# --------------------------------------------------------------------------- #
# Performance Harness
# --------------------------------------------------------------------------- #

PERF_HARNESS_TEMPLATE = '''"""
Auto-generated performance measurement harness for kernel optimization.
Interleaved A/B benchmark: ref → evo → evo → ref, alternating to cancel
thermal drift and systematic timing bias.
Generated by MetaInfer evolve-kernel orchestrator.
"""
import importlib.util
import json
import sys
import time
import traceback
from pathlib import Path

import torch


def load_kernel(filepath: str, fn_name: str = "{kernel_fn_name}"):
    spec = importlib.util.spec_from_file_location("_kernel_perf_mod", filepath)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, fn_name):
        raise ValueError(f"Function {{fn_name!r}} not found in {{filepath}}")
    return getattr(mod, fn_name)


def generate_benchmark_inputs():
    """Generate benchmark inputs at realistic sizes.

    Returns a list of dicts, each with kwargs for the kernel.
    AGENT MUST FILL IN realistic workload sizes.
    """
{bench_inputs_body}
    return bench_cases


def run_kernel(kernel_fn, test_case, warmup=5, repeat=20):
    """Time the kernel. AGENT FILLS IN with CUDA-event-based timing.

    Returns (median_time_ms, all_times_ms).
    """
{runner_body}


def main():
    if len(sys.argv) < 2:
        print(json.dumps({{"passed": False, "error": "Usage: python perf_harness.py <kernel.py>"}}))
        sys.exit(0)

    kernel_path = sys.argv[1]
    ref_path = "{ref_kernel_path}"

    try:
        ref_fn = load_kernel(ref_path, "{kernel_fn_name}")
        evo_fn = load_kernel(kernel_path, "{kernel_fn_name}")
    except Exception as e:
        print(json.dumps({{
            "passed": False,
            "error": f"Failed to load kernels: {{e}}",
            "traceback": traceback.format_exc()[:2000],
        }}))
        sys.exit(0)

    bench_cases = generate_benchmark_inputs()
    results = {{}}
    all_ref_times = []
    all_evo_times = []

    for tc in bench_cases:
        name = tc.get("name", "bench")
        try:
            ref_med, ref_times = run_kernel(ref_fn, tc, warmup={warmup}, repeat={repeat})
            evo_med, evo_times = run_kernel(evo_fn, tc, warmup={warmup}, repeat={repeat})

            # Interleaved re-measurement: ref-evo interleaved
            for _ in range({repeat}):
                _, rt = run_kernel(ref_fn, tc, warmup=0, repeat=1)
                all_ref_times.append(rt[0])
                _, et = run_kernel(evo_fn, tc, warmup=0, repeat=1)
                all_evo_times.append(et[0])

            speedup = ref_med / max(evo_med, 1e-6)
            results[name] = {{
                "ref_median_ms": round(ref_med, 6),
                "evo_median_ms": round(evo_med, 6),
                "speedup": round(speedup, 4),
            }}
        except Exception as e:
            results[name] = {{"error": str(e)[:300]}}

    # Aggregate
    import statistics
    ref_overall = statistics.median(all_ref_times) if all_ref_times else 0.0
    evo_overall = statistics.median(all_evo_times) if all_evo_times else 0.0
    overall_speedup = ref_overall / max(evo_overall, 1e-6)

    print(json.dumps({{
        "passed": True,
        "ref_median_ms": round(ref_overall, 6),
        "evo_median_ms": round(evo_overall, 6),
        "overall_speedup": round(overall_speedup, 4),
        "per_case": results,
        "num_cases": len(bench_cases),
    }}))


if __name__ == "__main__":
    main()
'''


def _fill_template(template: str, **kwargs: str) -> str:
    """Safe template fill — handles nested braces by using explicit keys."""
    result = template
    for key, value in kwargs.items():
        result = result.replace("{" + key + "}", value)
    return result


def build_correctness_harness_template(
    kernel_fn_name: str,
    ref_kernel_path: str,
    test_inputs_body: str = "    # AGENT: generate test cases covering all code paths\n    test_cases = []\n",
    ref_runner_body: str = "    # AGENT: call the reference kernel with test_case\n    torch.cuda.synchronize()\n    output = kernel_fn(**test_case)\n    torch.cuda.synchronize()\n",
    evo_runner_body: str = "    # AGENT: call the evolved kernel with test_case\n    torch.cuda.synchronize()\n    output = kernel_fn(**test_case)\n    torch.cuda.synchronize()\n",
    comparator_body: str = "    max_err = (ref_output - evo_output).abs().max().item()\n    passed = max_err < 1e-3\n    return passed, f'max_err={max_err}' if not passed else '', {'max_error': max_err}\n",
) -> str:
    return _fill_template(
        CORRECTNESS_HARNESS_TEMPLATE,
        kernel_fn_name=kernel_fn_name,
        ref_kernel_path=ref_kernel_path,
        test_inputs_body=test_inputs_body,
        ref_runner_body=ref_runner_body,
        evo_runner_body=evo_runner_body,
        comparator_body=comparator_body,
    )


def build_perf_harness_template(
    kernel_fn_name: str,
    ref_kernel_path: str,
    bench_inputs_body: str = "    # AGENT: generate realistic benchmark sizes\n    bench_cases = []\n",
    runner_body: str = "    start = torch.cuda.Event(enable_timing=True)\n    end = torch.cuda.Event(enable_timing=True)\n    times = []\n    for _ in range(warmup + repeat):\n        start.record()\n        kernel_fn(**test_case)\n        end.record()\n        torch.cuda.synchronize()\n        if _ >= warmup:\n            times.append(start.elapsed_time(end))\n    import statistics\n    return statistics.median(times), times\n",
    warmup: int = 5,
    repeat: int = 20,
) -> str:
    return _fill_template(
        PERF_HARNESS_TEMPLATE,
        kernel_fn_name=kernel_fn_name,
        ref_kernel_path=ref_kernel_path,
        bench_inputs_body=bench_inputs_body,
        runner_body=runner_body,
        warmup=str(warmup),
        repeat=str(repeat),
    )


# --------------------------------------------------------------------------- #
# Harness Execution
# --------------------------------------------------------------------------- #


def run_correctness_test(
    harness_path: Path,
    evolved_kernel_path: Path,
    timeout_s: int = 300,
) -> Tuple[bool, Dict[str, Any]]:
    """Run the correctness harness against an evolved kernel.

    Returns (passed, parsed_output_dict).
    """
    env = dict(os.environ)
    env["METAINFER_KERNEL_PATH"] = str(evolved_kernel_path)

    try:
        proc = subprocess.run(
            ["python3", str(harness_path), str(evolved_kernel_path)],
            capture_output=True, text=True,
            timeout=timeout_s, env=env,
        )
    except subprocess.TimeoutExpired:
        return False, {"passed": False, "error": f"Correctness harness timed out after {timeout_s}s"}
    except Exception as e:
        return False, {"passed": False, "error": f"Failed to run harness: {e!r}"}

    # Parse JSON from stdout (last line or last JSON object)
    stdout = proc.stdout or ""
    parsed = _extract_json(stdout)
    if parsed is None:
        # Try stderr
        stderr = proc.stderr or ""
        parsed_stderr = _extract_json(stderr)
        if parsed_stderr is None:
            return False, {
                "passed": False,
                "error": f"Harness produced no parseable JSON. stdout tail: {stdout[-500:]!r}",
            }
        parsed = parsed_stderr

    passed = bool(parsed.get("passed", False))
    return passed, parsed


def run_perf_test(
    harness_path: Path,
    kernel_path: Path,
    timeout_s: int = 600,
) -> Tuple[bool, Dict[str, Any]]:
    """Run the performance harness against a kernel.

    Returns (success, parsed_output_dict with exec_time_ms).
    """
    env = dict(os.environ)
    env["METAINFER_KERNEL_PATH"] = str(kernel_path)

    try:
        proc = subprocess.run(
            ["python3", str(harness_path), str(kernel_path)],
            capture_output=True, text=True,
            timeout=timeout_s, env=env,
        )
    except subprocess.TimeoutExpired:
        return False, {"passed": False, "error": f"Perf harness timed out after {timeout_s}s"}
    except Exception as e:
        return False, {"passed": False, "error": f"Failed to run perf harness: {e!r}"}

    stdout = proc.stdout or ""
    parsed = _extract_json(stdout)
    if parsed is None:
        stderr = proc.stderr or ""
        parsed = _extract_json(stderr) or {}
        parsed["passed"] = False

    passed = bool(parsed.get("passed", False))
    return passed, parsed


def _extract_json(text: str) -> Optional[Dict[str, Any]]:
    """Extract the last valid JSON object from text output."""
    candidates = []
    for ln in reversed(text.splitlines()):
        ln = ln.strip()
        if ln.startswith("{") and ln.endswith("}"):
            candidates.append(ln)
            if len(candidates) >= 10:
                break

    for c in candidates:
        try:
            obj = json.loads(c)
            if isinstance(obj, dict):
                return obj
        except json.JSONDecodeError:
            continue

    # Fallback: try to find JSON block in full text
    import re
    m = re.search(r'\{[^{}]*"passed"[^{}]*\}', text)
    if m:
        try:
            return json.loads(m.group(0))
        except json.JSONDecodeError:
            pass

    return None
